-- | Entry point for the call-graph explorer.
module Main
  ( main
  ) where

import Prelude

import DOM.HTML.Indexed.InputAcceptType
  ( extension
  )
import Data.Array (head)
import Data.Map as Map
import Data.Maybe (Maybe(..))
import Effect (Effect)
import Effect.Aff.Class
  ( class MonadAff
  , liftAff
  )
import Effect.Class (liftEffect)
import Halogen as H
import Halogen.Aff as HA
import Halogen.HTML as HH
import Halogen.HTML.Events as HE
import Halogen.HTML.Properties as HP
import Halogen.Subscription as HS
import Halogen.VDom.Driver (runUI)
import Web.Event.Event (Event)

import FFI.Cytoscape as Cy
import FFI.FileReader as FR
import Graph.Build (buildGraph)
import Graph.Cytoscape (toElements)
import Graph.DotParser as Dot
import Graph.Operations
  ( neighborhood
  , subgraph
  )
import Graph.Types
  ( Graph
  , NodeId
  , NodeKind
  , emptyGraph
  )

data Action
  = Initialize
  | FileSelected Event
  | NodeTapped NodeId
  | Focus
  | ShowAll
  | IncDepth
  | DecDepth
  | FitAll

type State =
  { fullGraph :: Graph
  , selectedNode :: Maybe NodeId
  , selectedLabel :: Maybe String
  , selectedKind :: Maybe NodeKind
  , focusDepth :: Int
  , focused :: Boolean
  }

initialState :: forall i. i -> State
initialState _ =
  { fullGraph: emptyGraph
  , selectedNode: Nothing
  , selectedLabel: Nothing
  , selectedKind: Nothing
  , focusDepth: 1
  , focused: false
  }

component
  :: forall q i o m
   . MonadAff m
  => H.Component q i o m
component =
  H.mkComponent
    { initialState
    , render
    , eval:
        H.mkEval
          H.defaultEval
            { handleAction = handleAction
            , initialize = Just Initialize
            }
    }

render
  :: forall m
   . State
  -> H.ComponentHTML Action () m
render state =
  HH.div_
    [ HH.div
        [ HP.id "toolbar" ]
        [ HH.label_
            [ HH.text "Load .dot"
            , HH.input
                [ HP.type_ HP.InputFile
                , HP.accept
                    (extension ".dot")
                , HE.onChange FileSelected
                ]
            ]
        , case state.selectedNode of
            Nothing -> HH.text ""
            Just _ ->
              if state.focused then
                HH.button
                  [ HE.onClick \_ -> ShowAll
                  ]
                  [ HH.text "Show All" ]
              else
                HH.button
                  [ HE.onClick \_ -> Focus ]
                  [ HH.text "Focus" ]
        , if state.focused then
            HH.span
              [ HP.id "depth-ctrl" ]
              [ HH.button
                  [ HE.onClick \_ -> DecDepth
                  ]
                  [ HH.text "-" ]
              , HH.span_
                  [ HH.text
                      ( "Depth: "
                          <> show
                            state.focusDepth
                      )
                  ]
              , HH.button
                  [ HE.onClick \_ -> IncDepth
                  ]
                  [ HH.text "+" ]
              ]
          else HH.text ""
        , HH.button
            [ HE.onClick \_ -> FitAll ]
            [ HH.text "Fit" ]
        ]
    , HH.div [ HP.id "main" ]
        [ HH.div [ HP.id "cy" ]
            [ if
                Map.isEmpty
                  state.fullGraph.nodes
              then
                HH.p
                  [ HP.id "placeholder" ]
                  [ HH.text
                      "Upload a .dot file \
                      \generated by \
                      \calligraphy."
                  ]
              else HH.text ""
            ]
        , HH.div
            [ HP.id "sidebar" ]
            [ case state.selectedLabel of
                Nothing ->
                  HH.p_
                    [ HH.text
                        "Click a node to \
                        \select. Then Focus \
                        \to see its \
                        \neighborhood."
                    ]
                Just label ->
                  HH.div_
                    [ HH.h3_
                        [ HH.text label ]
                    , case
                        state.selectedKind
                      of
                        Nothing ->
                          HH.text ""
                        Just kind ->
                          HH.span
                            [ HP.class_
                                ( HH.ClassName
                                    ( "kind-badge kind-"
                                        <> show
                                          kind
                                    )
                                )
                            ]
                            [ HH.text
                                (show kind)
                            ]
                    ]
            ]
        ]
    ]

-- | Subscribe to Cytoscape tap events via
-- | Halogen subscriptions.
subscribeTaps
  :: forall o m
   . MonadAff m
  => H.HalogenM State Action () o m Unit
subscribeTaps = do
  { emitter, listener } <- liftEffect
    HS.create
  liftEffect $ Cy.onNodeTap
    \nodeId -> HS.notify listener
      (NodeTapped nodeId)
  void $ H.subscribe emitter

handleAction
  :: forall o m
   . MonadAff m
  => Action
  -> H.HalogenM State Action () o m Unit
handleAction = case _ of
  Initialize ->
    liftEffect (Cy.initCytoscape "cy")

  FileSelected event -> do
    files <- liftEffect
      (FR.getFilesFromEvent event)
    case head files of
      Nothing -> pure unit
      Just file -> do
        dot <- liftAff (FR.readFile file)
        let
          parsed = Dot.parseDot dot
          graph = buildGraph
            parsed.nodes
            parsed.edges
        liftEffect $ Cy.setElements
          (toElements graph)
        subscribeTaps
        H.modify_ _
          { fullGraph = graph
          , selectedNode = Nothing
          , selectedLabel = Nothing
          , selectedKind = Nothing
          , focused = false
          }

  NodeTapped nodeId -> do
    state <- H.get
    let
      node = Map.lookup nodeId
        state.fullGraph.nodes
    liftEffect $ Cy.markRoot nodeId
    H.modify_ _
      { selectedNode = Just nodeId
      , selectedLabel =
          map _.label node
      , selectedKind = map _.kind node
      }

  Focus -> do
    state <- H.get
    case state.selectedNode of
      Nothing -> pure unit
      Just root -> do
        let
          keep = neighborhood
            state.focusDepth
            root
            state.fullGraph
          sub = subgraph keep
            state.fullGraph
        liftEffect $ Cy.setElements
          (toElements sub)
        liftEffect $ Cy.markRoot root
        H.modify_ _ { focused = true }

  ShowAll -> do
    state <- H.get
    liftEffect $ Cy.setElements
      (toElements state.fullGraph)
    case state.selectedNode of
      Nothing -> pure unit
      Just root ->
        liftEffect $ Cy.markRoot root
    H.modify_ _ { focused = false }

  IncDepth -> do
    state <- H.get
    let
      d = min 5 (state.focusDepth + 1)
    H.modify_ _ { focusDepth = d }
    when state.focused do
      handleAction Focus

  DecDepth -> do
    state <- H.get
    let
      d = max 1 (state.focusDepth - 1)
    H.modify_ _ { focusDepth = d }
    when state.focused do
      handleAction Focus

  FitAll -> liftEffect Cy.fitAll

main :: Effect Unit
main =
  HA.runHalogenAff do
    body <- HA.awaitBody
    runUI component unit body
